name: Build Engine

on: workflow_dispatch

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: xpol/setup-lua@v1
        with:
          lua-version: "5.3.5"
      - uses: leafo/gh-actions-luarocks@v4
      - name: Install Dependencies
        run: |
         echo Starting LuaGL Install Process
         luarocks install luagl
      - name: Compile Code
        run: |
         echo Starting Lua Code Compilation Process
         luac -o Source.luac source/Source.lua
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Source
          path: .
