name: Build Engine

on: workflow_dispatch

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.3"
      - uses: leafo/gh-actions-luarocks@v4
        with:
          luarocksVersion: "3.1.3"
      - name: Install Dependencies
        run: |
         echo Starting LuaGL Install Process
         luarocks install luagl GLUT_DIR=/usr/local
      - name: Compile Code
        run: |
         echo Starting Lua Code Compilation Process
         luac -o Source.luac source/Source.lua
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Source
          path: .
